# Generated by Django 3.2.7 on 2021-11-18 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('pump_state', models.BooleanField(default=False)),
                ('comp_state', models.BooleanField(default=False)),
                ('light_state', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pump_state', models.BooleanField(default=False)),
                ('comp_state', models.BooleanField(default=False)),
                ('light_state', models.BooleanField(default=False)),
                ('device_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicestate')),
            ],
        ),
    ]
